version: '3.1'

services:
  mysql:
    image: mysql:latest
    environment:
      MYSQL_ROOT_USER: root
      MYSQL_ROOT_PASSWORD: secret
      MYSQL_DATABASE: account
      MYSQL_USER: account
      MYSQL_PASSWORD: 123456
    ports:
      - "3306:3306"
  cache:
    image: redis:latest
    ports:
      - "6379:6379"