apiVersion: apps/v1
kind: Deployment
metadata:
  name: ms-account-group61
spec:
  replicas: 2
  selector:
    matchLabels:
      app: ms-account-group61
  template:
    metadata:
      labels:
        app: ms-account-group61
    spec:
      containers:
        - name: ms-account-group61
          image: 057196872298.dkr.ecr.us-east-2.amazonaws.com/ms-account-group61:latest
          ports:
            - containerPort: 8080