server:
  port: 8081
spring:
  h2:
    console.enabled: true
  datasource:
    url: jdbc:h2:mem:mydb
    username: accounts
    password: 12345
    driverClassName: org.h2.Driver
  jpa:
    database-platform: org.hibernate.dialect.H2Dialect